import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { ShieldAlert } from "lucide-react-native";
import { api } from "../api";
import { canMutate } from "../access";
import { ConfirmSheet, ScreenHeader, SectionCard, StatePanel } from "../components";
import { useSession } from "../session";
import { palette, radius, spacing } from "../theme";

type Confirmation = { title: string; message: string; action: () => Promise<void> } | null;
function newKey(): string { return globalThis.crypto?.randomUUID?.() ?? `live-${Date.now()}-${Math.random().toString(16).slice(2)}`; }

export default function LiveExecutionScreen() {
  const { session } = useSession();
  const queryClient = useQueryClient();
  const [label, setLabel] = useState(""); const [provider, setProvider] = useState<"okx" | "binance">("okx"); const [marketType, setMarketType] = useState<"spot" | "swap">("spot"); const [apiKey, setApiKey] = useState(""); const [apiSecret, setApiSecret] = useState(""); const [passphrase, setPassphrase] = useState(""); const [withdrawalConfirmed, setWithdrawalConfirmed] = useState(false); const [ipConfirmed, setIpConfirmed] = useState(false);
  const [maxNotional, setMaxNotional] = useState("100"); const [maxPositions, setMaxPositions] = useState("1"); const [maxLeverage, setMaxLeverage] = useState("1"); const [symbols, setSymbols] = useState("BTC-USDT");
  const [bindStrategy, setBindStrategy] = useState(""); const [bindConnection, setBindConnection] = useState(""); const [challengeCode, setChallengeCode] = useState(""); const [orderConnection, setOrderConnection] = useState(""); const [orderSymbol, setOrderSymbol] = useState("BTC-USDT"); const [orderSide, setOrderSide] = useState<"buy" | "sell">("buy"); const [orderType, setOrderType] = useState<"market" | "limit">("market"); const [orderAmount, setOrderAmount] = useState("100"); const [orderPrice, setOrderPrice] = useState(""); const [confirmation, setConfirmation] = useState<Confirmation>(null);
  const liveOrderSubmission = useRef<{ fingerprint: string; key: string } | null>(null);
  const access = useQuery({ queryKey: ["mobile", session?.tenantId, "access"], queryFn: api.access, enabled: Boolean(session) });
  const status = useQuery({ queryKey: ["mobile", session?.tenantId, "live", "status"], queryFn: api.liveStatus, enabled: Boolean(session) });
  const connections = useQuery({ queryKey: ["mobile", session?.tenantId, "live", "connections"], queryFn: api.liveConnections, enabled: Boolean(session) });
  const policy = useQuery({ queryKey: ["mobile", session?.tenantId, "live", "policy"], queryFn: api.liveRiskPolicy, enabled: Boolean(session) });
  const bindings = useQuery({ queryKey: ["mobile", session?.tenantId, "live", "bindings"], queryFn: api.liveBindings, enabled: Boolean(session) });
  const orders = useQuery({ queryKey: ["mobile", session?.tenantId, "live", "orders", orderConnection], queryFn: () => api.liveOrders(orderConnection || undefined), enabled: Boolean(session) });
  const livePositions = useQuery({ queryKey: ["mobile", session?.tenantId, "live", "positions", orderConnection], queryFn: () => api.liveConnectionPositions(orderConnection), enabled: Boolean(session && orderConnection) });
  const createConnection = useMutation({ mutationFn: () => api.createLiveConnection({ label: label.trim(), provider, market_type: marketType, api_key: apiKey, api_secret: apiSecret, ...(provider === "okx" ? { passphrase } : {}), withdrawal_disabled_confirmed: withdrawalConfirmed, ip_allowlist_confirmed: ipConfirmed }) });
  const savePolicy = useMutation({ mutationFn: () => api.saveLiveRiskPolicy({ max_order_notional: Number(maxNotional), max_open_positions: Number(maxPositions), max_leverage: Number(maxLeverage), allowed_symbols: symbols.split(",").map((item) => item.trim().toUpperCase()).filter(Boolean) }) });
  const createBinding = useMutation({ mutationFn: () => api.createLiveBinding({ strategy_id: bindStrategy.trim(), connection_id: bindConnection }) });
  const liveOrderKey = () => {
    const fingerprint = JSON.stringify({ connectionId: orderConnection, symbol: orderSymbol.trim().toUpperCase(), side: orderSide, type: orderType, amount: orderAmount, price: orderPrice });
    if (liveOrderSubmission.current?.fingerprint !== fingerprint) liveOrderSubmission.current = { fingerprint, key: newKey() };
    return liveOrderSubmission.current.key;
  };
  const requestChallenge = useMutation({ mutationFn: api.requestStartupAuthorizationChallenge, onSettled: () => setChallengeCode("") }); const confirmChallenge = useMutation({ mutationFn: () => api.confirmStartupAuthorization({ challenge_code: challengeCode.trim() }) }); const revokeAuthorization = useMutation({ mutationFn: api.revokeStartupAuthorization }); const revokeBinding = useMutation({ mutationFn: api.revokeLiveBinding }); const createOrder = useMutation({ mutationFn: () => api.createLiveOrder({ connection_id: orderConnection, symbol: orderSymbol.trim().toUpperCase(), side: orderSide, type: orderType, quote_amount: Number(orderAmount), ...(orderType === "limit" ? { price: Number(orderPrice) } : {}) }, liveOrderKey()), onSuccess: () => { liveOrderSubmission.current = null; } });
  const canConnections = canMutate(access.data, "connection.manage"); const canTrade = canMutate(access.data, "trade.execute");
  const invalidate = () => void queryClient.invalidateQueries({ queryKey: ["mobile", session?.tenantId, "live"] });
  useEffect(() => { if (!orderConnection && connections.data?.[0]) setOrderConnection(connections.data[0].id); if (!bindConnection && connections.data?.[0]) setBindConnection(connections.data[0].id); }, [bindConnection, connections.data, orderConnection]);
  const createConnectionAction = async () => { if (!label.trim() || !apiKey || !apiSecret || !withdrawalConfirmed || !ipConfirmed || (provider === "okx" && !passphrase)) throw new Error("必须填写凭据，并逐项确认已禁用提现和已设置 IP 白名单。"); try { await createConnection.mutateAsync(); invalidate(); } finally { setApiKey(""); setApiSecret(""); setPassphrase(""); } };
  const savePolicyAction = async () => { if ([maxNotional, maxPositions, maxLeverage].some((value) => !Number.isFinite(Number(value)) || Number(value) <= 0) || !symbols.trim()) throw new Error("风险上限必须为正数，且至少允许一个交易对。"); await savePolicy.mutateAsync(); invalidate(); };
  const bindAction = async () => { if (!bindStrategy || !bindConnection) throw new Error("请填写策略 ID 并选择连接。"); await createBinding.mutateAsync(); invalidate(); };
  const confirmAuthorizationAction = async () => { if (!challengeCode.trim()) throw new Error("请输入服务器签发的挑战码。"); try { await confirmChallenge.mutateAsync(); invalidate(); } finally { setChallengeCode(""); } };
  const submitOrderAction = async () => { if (!status.data?.live_trading_enabled || !status.data.authorization_active) throw new Error("服务端尚未同时启用实盘交易和有效授权。"); if (!orderConnection || !orderSymbol.trim() || Number(orderAmount) <= 0 || (orderType === "limit" && Number(orderPrice) <= 0)) throw new Error("请完整填写连接、交易对、金额和限价。 "); await createOrder.mutateAsync(); invalidate(); };
  const runConfirmation = async () => { if (!confirmation) return; try { await confirmation.action(); setConfirmation(null); } catch (error) { Alert.alert("操作未完成", error instanceof Error ? error.message : "服务器拒绝了本次操作。"); } };
  if (status.isLoading) return <StatePanel description="正在读取服务端实盘安全状态。" title="实盘执行" />;
  return <ScrollView contentContainerStyle={styles.content} style={styles.page}>
    <ScreenHeader subtitle="实盘仅在服务器开关、风险策略、连接绑定和短时授权均满足时可用。" title="实盘执行" />
    <View style={[styles.status, { backgroundColor: status.data?.live_trading_enabled && status.data.authorization_active ? palette.positiveSoft : palette.warningSoft }]}><ShieldAlert color={status.data?.live_trading_enabled && status.data.authorization_active ? palette.positive : palette.warning} size={22} /><View style={{ flex: 1 }}><Text style={styles.statusTitle}>{status.data?.live_trading_enabled ? "实盘开关已启用" : "实盘开关未启用"}</Text><Text style={styles.statusText}>{status.data?.authorization_active ? `授权有效至 ${status.data.authorization_expires_at ?? "—"}` : "没有有效实盘授权"}</Text>{status.data?.gate_reasons.map((reason) => <Text key={reason} style={styles.gate}>• {reason}</Text>)}</View></View>
    <SectionCard title="实盘连接"><Text style={styles.warning}>创建连接前必须确认：交易所 API Key 已禁用提现，并仅允许服务器 IP 白名单。</Text><Field label="连接标签" onChangeText={setLabel} value={label} /><Choices choices={[{ label: "OKX", value: "okx" }, { label: "Binance", value: "binance" }]} onSelect={setProvider} value={provider} /><Choices choices={[{ label: "现货", value: "spot" }, { label: "合约", value: "swap" }]} onSelect={setMarketType} value={marketType} /><Field label="API Key" onChangeText={setApiKey} sensitive value={apiKey} /><Field label="API Secret" onChangeText={setApiSecret} sensitive value={apiSecret} />{provider === "okx" ? <Field label="Passphrase" onChangeText={setPassphrase} sensitive value={passphrase} /> : null}<Toggle label="我确认 API Key 已禁用提现" onChange={setWithdrawalConfirmed} value={withdrawalConfirmed} /><Toggle label="我确认已设置服务器 IP 白名单" onChange={setIpConfirmed} value={ipConfirmed} /><Action disabled={!canConnections} label="创建实盘连接" onPress={() => setConfirmation({ title: "创建实盘连接", message: "凭据将发送到服务器保险库。确认上述提现禁用和 IP 白名单均已完成。", action: createConnectionAction })} /></SectionCard>
    <SectionCard title="服务器风险策略"><Field label="单笔最大名义金额" onChangeText={setMaxNotional} value={maxNotional} /><Field label="最大开放仓位" onChangeText={setMaxPositions} value={maxPositions} /><Field label="最大杠杆" onChangeText={setMaxLeverage} value={maxLeverage} /><Field label="允许交易对（逗号分隔）" onChangeText={setSymbols} value={symbols} /><Action disabled={!canConnections} label="保存风控策略" onPress={() => setConfirmation({ title: "保存风险策略", message: "新的服务器风险策略会限制所有后续实盘订单。", action: savePolicyAction })} />{policy.data ? <Text style={styles.caption}>当前：{policy.data.allowed_symbols.join(" · ")} · 单笔 {policy.data.max_order_notional}</Text> : null}</SectionCard>
    <SectionCard title="策略绑定"><Field label="策略 ID" onChangeText={setBindStrategy} value={bindStrategy} /><ConnectionChoices connections={connections.data ?? []} onSelect={setBindConnection} value={bindConnection} /><Action disabled={!canConnections} label="创建绑定" onPress={() => setConfirmation({ title: "绑定策略", message: "确认把该策略绑定到选定实盘连接。", action: bindAction })} />{(bindings.data ?? []).map((binding) => <View key={binding.id} style={styles.listRow}><Text style={styles.row}>{binding.strategy_id} · {binding.connection_id} · {binding.active ? "有效" : "已撤销"}</Text>{binding.active ? <Action disabled={!canConnections} label="撤销绑定" onPress={() => setConfirmation({ title: "撤销绑定", message: "撤销后策略不能再通过该连接执行。", action: async () => { await revokeBinding.mutateAsync(binding.id); invalidate(); } })} /> : null}</View>)}</SectionCard>
    <SectionCard title="启动授权"><Text style={styles.caption}>挑战码由服务器签发且短时有效，不会缓存为本地授权状态。</Text><Action disabled={!canTrade} label="请求挑战码" onPress={() => void requestChallenge.mutateAsync().then((challenge) => Alert.alert("挑战码已签发", `请按安全渠道确认挑战码：${challenge.challenge_code}`)).catch((error: Error) => Alert.alert("请求失败", error.message))} /><Field label="挑战码" onChangeText={setChallengeCode} sensitive value={challengeCode} /><Action disabled={!canTrade} label="确认授权" onPress={() => setConfirmation({ title: "确认实盘授权", message: "确认后服务器会启用短时实盘授权。", action: confirmAuthorizationAction })} /><Action disabled={!canTrade || !status.data?.authorization_active} label="撤销当前授权" destructive onPress={() => setConfirmation({ title: "撤销实盘授权", message: "撤销后将立刻禁止新实盘订单。", action: async () => { await revokeAuthorization.mutateAsync(); invalidate(); } })} /></SectionCard>
    <SectionCard title="手动实盘订单"><ConnectionChoices connections={connections.data ?? []} onSelect={setOrderConnection} value={orderConnection} /><Field label="交易对" onChangeText={setOrderSymbol} value={orderSymbol} /><Choices choices={[{ label: "买入", value: "buy" }, { label: "卖出", value: "sell" }]} onSelect={setOrderSide} value={orderSide} /><Choices choices={[{ label: "市价", value: "market" }, { label: "限价", value: "limit" }]} onSelect={setOrderType} value={orderType} /><Field label="金额（USDT）" onChangeText={setOrderAmount} value={orderAmount} />{orderType === "limit" ? <Field label="限价" onChangeText={setOrderPrice} value={orderPrice} /> : null}<Action disabled={!canTrade || !status.data?.live_trading_enabled || !status.data?.authorization_active} label="提交实盘订单" onPress={() => setConfirmation({ title: "提交实盘订单", message: "将创建一笔受服务器风险策略与幂等保护约束的实盘订单。", action: submitOrderAction })} /></SectionCard>
    <SectionCard title="只读仓位">{livePositions.isError ? <Text style={styles.warning}>{(livePositions.error as Error).message}</Text> : (livePositions.data ?? []).length ? (livePositions.data ?? []).map((position, index) => <Text key={`${position.symbol ?? "position"}-${index}`} style={styles.row}>{position.symbol ?? "—"} · {position.side ?? "—"} · 合约 {position.contracts ?? "—"} · 名义金额 {position.notional ?? "—"}</Text>) : <Text style={styles.caption}>选择实盘连接后显示服务器返回的只读仓位。</Text>}</SectionCard>
    <SectionCard title="只读订单"><Action label="刷新订单" onPress={() => void orders.refetch()} />{(orders.data ?? []).map((order) => <View key={order.id} style={styles.listRow}><Text style={styles.row}>{order.id} · {order.status} · {order.created_at}</Text><Action disabled={!canTrade} label="刷新交易所状态" onPress={() => void api.refreshLiveOrder(order.id).then(() => orders.refetch()).catch((error: Error) => Alert.alert("刷新失败", error.message))} /></View>)}</SectionCard>
    <ConfirmSheet confirming={false} destructive visible={Boolean(confirmation)} title={confirmation?.title ?? "确认"} message={confirmation?.message ?? ""} confirmLabel="确认" onCancel={() => setConfirmation(null)} onConfirm={() => void runConfirmation()} />
  </ScrollView>;
}

function Field({ label, onChangeText, sensitive = false, value }: { label: string; value: string; sensitive?: boolean; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} autoCapitalize="none" onChangeText={onChangeText} secureTextEntry={sensitive} style={styles.input} value={value} /></View>; }
function Toggle({ label, onChange, value }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: value }} onPress={() => onChange(!value)} style={styles.toggle}><Text style={styles.row}>{label}</Text><View style={[styles.checkbox, value && styles.checkboxOn]}>{value ? <Text style={styles.checkboxText}>✓</Text> : null}</View></Pressable>; }
function Choices<T extends string>({ choices, onSelect, value }: { choices: { label: string; value: T }[]; value: T; onSelect: (value: T) => void }) { return <View style={styles.choices}>{choices.map((choice) => <Pressable accessibilityRole="button" key={choice.value} onPress={() => onSelect(choice.value)} style={[styles.choice, choice.value === value && styles.choiceOn]}><Text style={[styles.choiceText, choice.value === value && styles.choiceTextOn]}>{choice.label}</Text></Pressable>)}</View>; }
function ConnectionChoices({ connections, onSelect, value }: { connections: { id: string; label: string }[]; value: string; onSelect: (value: string) => void }) { return <View style={styles.choices}>{connections.map((connection) => <Pressable accessibilityRole="button" key={connection.id} onPress={() => onSelect(connection.id)} style={[styles.choice, connection.id === value && styles.choiceOn]}><Text style={[styles.choiceText, connection.id === value && styles.choiceTextOn]}>{connection.label}</Text></Pressable>)}</View>; }
function Action({ disabled, destructive = false, label, onPress }: { label: string; onPress: () => void; disabled?: boolean; destructive?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.action, destructive && styles.actionDestructive, disabled && styles.disabled]}><Text style={[styles.actionText, destructive && styles.actionTextDestructive]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({ page: { backgroundColor: palette.canvas, flex: 1 }, content: { gap: spacing.md, padding: spacing.md, paddingBottom: spacing.xl }, status: { alignItems: "flex-start", borderRadius: radius.md, flexDirection: "row", gap: spacing.sm, padding: spacing.md }, statusTitle: { color: palette.text, fontSize: 15, fontWeight: "800" }, statusText: { color: palette.textMuted, fontSize: 12, marginTop: 3 }, gate: { color: palette.warning, fontSize: 12, marginTop: 3 }, warning: { color: palette.warning, fontSize: 13, lineHeight: 20 }, caption: { color: palette.textMuted, fontSize: 12, lineHeight: 19 }, field: { gap: spacing.xs }, label: { color: palette.textMuted, fontSize: 12, fontWeight: "700" }, input: { backgroundColor: palette.canvas, borderColor: palette.border, borderRadius: radius.sm, borderWidth: 1, color: palette.text, minHeight: 46, paddingHorizontal: spacing.sm }, toggle: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", minHeight: 44 }, checkbox: { borderColor: palette.border, borderRadius: 5, borderWidth: 1, height: 24, width: 24, alignItems: "center", justifyContent: "center" }, checkboxOn: { backgroundColor: palette.primary, borderColor: palette.primary }, checkboxText: { color: palette.canvas, fontWeight: "800" }, choices: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, choice: { borderColor: palette.border, borderRadius: radius.pill, borderWidth: 1, minHeight: 40, justifyContent: "center", paddingHorizontal: spacing.sm }, choiceOn: { backgroundColor: palette.primarySoft, borderColor: palette.primary }, choiceText: { color: palette.textMuted, fontSize: 12, fontWeight: "800" }, choiceTextOn: { color: palette.primary }, action: { alignItems: "center", borderColor: palette.primary, borderRadius: radius.sm, borderWidth: 1, justifyContent: "center", minHeight: 46, paddingHorizontal: spacing.md }, actionDestructive: { borderColor: palette.negative }, actionText: { color: palette.primary, fontSize: 14, fontWeight: "800" }, actionTextDestructive: { color: palette.negative }, disabled: { opacity: 0.4 }, listRow: { borderTopColor: palette.border, borderTopWidth: 1, gap: spacing.sm, paddingTop: spacing.sm }, row: { color: palette.text, fontSize: 13, lineHeight: 20 }, });
