import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { api } from "../api";
import { isPlatformAdmin, platformAdminGate } from "../access";
import { ScreenHeader, SectionCard, StatePanel } from "../components";
import { useSession } from "../session";
import { palette, radius, spacing } from "../theme";

export default function PlatformAdminScreen() {
  const { session } = useSession(); const queryClient = useQueryClient(); const [tenantId, setTenantId] = useState(""); const [tenantType, setTenantType] = useState<"personal" | "enterprise">("enterprise"); const [organizationName, setOrganizationName] = useState(""); const [planCode, setPlanCode] = useState(""); const [planName, setPlanName] = useState(""); const [days, setDays] = useState("30"); const [cents, setCents] = useState("0"); const [planId, setPlanId] = useState(""); const [endsAt, setEndsAt] = useState(""); const [agreementNumber, setAgreementNumber] = useState(""); const [revenueRate, setRevenueRate] = useState("0.2"); const [cycleDays, setCycleDays] = useState("30"); const [startsAt, setStartsAt] = useState("");
  const access = useQuery({ queryKey: ["mobile", session?.tenantId, "access"], queryFn: api.access, enabled: Boolean(session) }); const tenants = useQuery({ queryKey: ["mobile", "admin", "tenants"], queryFn: api.adminTenants, enabled: isPlatformAdmin(access.data) }); const plans = useQuery({ queryKey: ["mobile", "admin", "plans"], queryFn: api.adminPlans, enabled: isPlatformAdmin(access.data) }); const audit = useQuery({ queryKey: ["mobile", "admin", "audit", 100], queryFn: () => api.adminAudit(100), enabled: isPlatformAdmin(access.data) });
  const refresh = () => void queryClient.invalidateQueries({ queryKey: ["mobile", "admin"] }); const updateProfile = useMutation({ mutationFn: () => api.updateTenantProfile({ tenant_id: tenantId, tenant_type: tenantType, organization_name: organizationName.trim() || undefined }), onSuccess: refresh }); const createPlan = useMutation({ mutationFn: () => api.createPlan({ code: planCode, name: planName, duration_days: Number(days), price_cents: Number(cents), currency: "CNY" }), onSuccess: refresh }); const grant = useMutation({ mutationFn: () => api.grantSubscription({ tenant_id: tenantId, plan_id: planId, ends_at: endsAt }), onSuccess: refresh }); const agreement = useMutation({ mutationFn: () => api.createEnterpriseAgreement({ tenant_id: tenantId, agreement_number: agreementNumber, revenue_share_rate: revenueRate, settlement_cycle_days: Number(cycleDays), starts_at: startsAt }), onSuccess: refresh });
  const execute = (label: string, action: () => Promise<unknown>) => void action().catch((error: Error) => Alert.alert(`${label}失败`, error.message));
  const adminGate = platformAdminGate(access.data);
  if (access.isLoading) return <StatePanel description="正在验证平台管理员身份。" title="平台管理" />;
  if (!adminGate.readable) return <StatePanel description="平台管理只对服务端标记的 platform admin 可见；深链也不会绕过此限制。" title="无平台权限" tone="error" />;
  return <ScrollView contentContainerStyle={styles.content} style={styles.page}><ScreenHeader subtitle="平台独立 API：租户、订阅计划、企业合约与全局审计。" title="平台管理" /><SectionCard title="租户档案">{(tenants.data ?? []).map((tenant) => <Pressable accessibilityRole="button" key={tenant.id} onPress={() => { setTenantId(tenant.id); setTenantType(tenant.tenant_type); setOrganizationName(tenant.organization_name ?? ""); }} style={styles.tenant}><View style={{ flex: 1 }}><Text style={styles.primary}>{tenant.organization_name ?? tenant.name}</Text><Text style={styles.secondary}>{tenant.id} · {tenant.tenant_type} · {tenant.access.status}</Text></View></Pressable>)}<Field label="租户 ID" onChangeText={setTenantId} value={tenantId} /><Choices onSelect={setTenantType} value={tenantType} /><Field label="企业名称（企业租户必填）" onChangeText={setOrganizationName} value={organizationName} /><Action disabled={!adminGate.mutationAllowed} label="更新租户档案" onPress={() => execute("更新档案", updateProfile.mutateAsync)} /></SectionCard><SectionCard title="订阅计划"><Field label="计划代码" onChangeText={setPlanCode} value={planCode} /><Field label="计划名称" onChangeText={setPlanName} value={planName} /><Field label="时长（天）" onChangeText={setDays} value={days} /><Field label="价格（分）" onChangeText={setCents} value={cents} /><Action disabled={!adminGate.mutationAllowed} label="创建计划" onPress={() => execute("创建计划", createPlan.mutateAsync)} />{(plans.data ?? []).map((plan) => <Pressable accessibilityRole="button" key={plan.id} onPress={() => setPlanId(plan.id)} style={styles.tenant}><Text style={styles.primary}>{plan.name} · {plan.code}</Text><Text style={styles.secondary}>{plan.duration_days} 天 · {plan.price_cents} {plan.currency}</Text></Pressable>)}</SectionCard><SectionCard title="授予订阅"><Field label="选中租户 ID" onChangeText={setTenantId} value={tenantId} /><Field label="选中计划 ID" onChangeText={setPlanId} value={planId} /><Field label="结束时间（ISO 8601）" onChangeText={setEndsAt} value={endsAt} /><Action disabled={!adminGate.mutationAllowed} label="授予订阅" onPress={() => execute("授予订阅", grant.mutateAsync)} /></SectionCard><SectionCard title="企业合约"><Field label="协议编号" onChangeText={setAgreementNumber} value={agreementNumber} /><Field label="分成比例（0-1）" onChangeText={setRevenueRate} value={revenueRate} /><Field label="结算周期（天）" onChangeText={setCycleDays} value={cycleDays} /><Field label="开始时间（ISO 8601）" onChangeText={setStartsAt} value={startsAt} /><Action disabled={!adminGate.mutationAllowed} label="创建企业合约" onPress={() => execute("创建合约", agreement.mutateAsync)} /></SectionCard><SectionCard title="全局审计">{(audit.data ?? []).map((event) => <View key={event.id} style={styles.audit}><Text style={styles.primary}>{event.action} · {event.outcome}</Text><Text style={styles.secondary}>{event.tenant_id ?? "平台"} · {event.created_at}</Text></View>)}</SectionCard></ScrollView>;
}
function Field({ label, onChangeText, value }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} autoCapitalize="none" onChangeText={onChangeText} style={styles.input} value={value} /></View>; }
function Choices({ onSelect, value }: { value: "personal" | "enterprise"; onSelect: (value: "personal" | "enterprise") => void }) { return <View style={styles.choices}>{(["personal", "enterprise"] as const).map((item) => <Pressable accessibilityRole="button" key={item} onPress={() => onSelect(item)} style={[styles.choice, value === item && styles.choiceActive]}><Text style={[styles.choiceText, value === item && styles.choiceTextActive]}>{item}</Text></Pressable>)}</View>; }
function Action({ disabled = false, label, onPress }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.action, disabled && { opacity: 0.45 }]}><Text style={styles.actionText}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ page: { backgroundColor: palette.canvas, flex: 1 }, content: { gap: spacing.md, padding: spacing.md, paddingBottom: spacing.xl }, tenant: { borderTopColor: palette.border, borderTopWidth: 1, gap: spacing.xs, minHeight: 48, justifyContent: "center", paddingVertical: spacing.sm }, primary: { color: palette.text, fontSize: 13, fontWeight: "800" }, secondary: { color: palette.textMuted, fontSize: 11, lineHeight: 18 }, field: { gap: spacing.xs }, label: { color: palette.textMuted, fontSize: 12, fontWeight: "700" }, input: { backgroundColor: palette.canvas, borderColor: palette.border, borderRadius: radius.sm, borderWidth: 1, color: palette.text, minHeight: 46, paddingHorizontal: spacing.sm }, choices: { flexDirection: "row", gap: spacing.xs }, choice: { borderColor: palette.border, borderRadius: radius.pill, borderWidth: 1, minHeight: 40, justifyContent: "center", paddingHorizontal: spacing.sm }, choiceActive: { backgroundColor: palette.primarySoft, borderColor: palette.primary }, choiceText: { color: palette.textMuted, fontSize: 12 }, choiceTextActive: { color: palette.primary }, action: { alignItems: "center", borderColor: palette.primary, borderRadius: radius.sm, borderWidth: 1, justifyContent: "center", minHeight: 46 }, actionText: { color: palette.primary, fontSize: 14, fontWeight: "800" }, audit: { borderTopColor: palette.border, borderTopWidth: 1, paddingVertical: spacing.sm }, });
